spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/(?<segment>.*), /$\{segment}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/login
            - Path=/forgot-password
            - Path=/reset-password
          filters:
            - RewritePath=/login, /login
            - RewritePath=/forgot-password, /forgot-password
            - RewritePath=/reset-password, /reset-password

server:
  port: 8080
